version = 9.0-SNAPSHOT
zzName = jros1client
zzNamespace = lambdaprime
zzCopyright = jrosclient
zzJavaVersion = 17
zzDescription = Java module to interact with ROS1 (Robot Operating System)
zzUrl = http://portal2.atwebpages.com/jrosclient
zzRepoUrl = https://github.com/lambdaprime/jros1client
zzDevName = lambdaprime
zzDevEmail = intid@protonmail.com
zzApiDependencies = io.github.lambdaprime:jrosclient:10.0-SNAPSHOT,io.github.lambdaprime:jros1messages:5.0-SNAPSHOT,io.github.lambdaprime:ICE:3.0,org.apache.xmlrpc:xmlrpc-client:3.1.3,org.apache.xmlrpc:xmlrpc-server:3.1.3
zzTestDependencies = io.github.lambdaprime:jrosclient.tests:10.0-SNAPSHOT,io.github.lambdaprime:id.xfunctiontests:1.0
zzMinTestCoverage = 0.3
zzJavadocLinks = http://portal2.atwebpages.com/jrosclient/javadoc/jros1messages/,http://portal2.atwebpages.com/jrosclient/javadoc/jrosmessages/,http://portal2.atwebpages.com/jrosclient/javadoc/jrosclient/
zzJavadocInheritFrom = jrosclient
zzRequiredGradleVersion = 8.3
zzFilesToPackage = README.md,LICENSE-2.0.txt,jros1client/src/jros1client